# Generated by Django 5.1.3 on 2025-02-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelvendor',
            options={},
        ),
        migrations.AlterModelTable(
            name='hotelvendor',
            table='Hotel Vendor',
        ),
    ]
