# Generated by Django 5.1.3 on 2025-02-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_hotelvendor_options_alter_hotelvendor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ameneties',
            table='vendors_ameneties',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='vendors_hotel',
        ),
    ]
