# Generated by Django 5.1.3 on 2025-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_ameneties_table_alter_hotel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimages',
            name='selected_image',
            field=models.BooleanField(default=False),
        ),
    ]
