# Generated by Django 5.1.3 on 2025-02-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_hotelimages_selected_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimages',
            name='selected_image',
        ),
    ]
