# Generated by Django 5.1.3 on 2025-02-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_remove_hotelimages_selected_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimages',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
